// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA78YwAyEuKnQPkgb3JOO5k3C_hzJ3DQCg',
    appId: '1:834216153243:web:a7372a79abfaf9512cf63e',
    messagingSenderId: '834216153243',
    projectId: 'tybarestaurant',
    authDomain: 'tybarestaurant.firebaseapp.com',
    storageBucket: 'tybarestaurant.appspot.com',
    measurementId: 'G-2RBSVYEQKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT3-6RoeiL3JIX0Z7qMLDfq_amrYiAbF0',
    appId: '1:834216153243:android:a140896510f4b8c42cf63e',
    messagingSenderId: '834216153243',
    projectId: 'tybarestaurant',
    storageBucket: 'tybarestaurant.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANWbyRCkIsZbOym0lGkfmCaHCuh8tV2pQ',
    appId: '1:834216153243:ios:adf790e145abb6dc2cf63e',
    messagingSenderId: '834216153243',
    projectId: 'tybarestaurant',
    storageBucket: 'tybarestaurant.appspot.com',
    iosClientId: '834216153243-9q6ifo8jgak5mic38nntm8egr1o1vogc.apps.googleusercontent.com',
    iosBundleId: 'com.example.tybaGreatApp',
  );
}
